# Dependabot configuration for automatic dependency updates
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Monitor GitHub Actions for version updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "vancodocton"
    assignees:
      - "vancodocton"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    # Group related actions updates together
    groups:
      actions-major:
        patterns:
          - "*"
        update-types:
          - "major"
      actions-minor:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"