name: "CI CD workflows"

on:
  push:
    branches:
      - "main"
    paths:
      - '.github/workflows/CI_CD.yml'
      - 'src/IdentityServer/**'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - "main"
    paths:
      - '.github/workflows/CI_CD.yml'
      - 'src/IdentityServer/**'
  workflow_dispatch:   
    inputs:
      isCD:
        description: "Run CD:"
        required: true
        default: 'no'
        type: choice
        options:
          - 'no'
          - 'publish'
          - 'stage'
          - 'production'
 
env:
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 6.0.x
  SOLUTION_FILE: FinalProject.sln

jobs:
  dotnet_CI:
    name: .Net CI
    strategy:
      fail-fast: false
      matrix:
        Solution: 
        - IdentityServer:
          path: src/IdentityServer/FinalProject.IdentityServer.slnf
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

    - name: Restore
      run: |
        dotnet tool restore
        dotnet restore ${{ matrix.Solution.path }}

    - name: Build
      run: dotnet build "${{ matrix.Solution.path }}" --configuration ${{ env.CONFIGURATION }} --no-restore

    - name: Test
      run: dotnet test "${{ matrix.Solution.path }}" --no-build --verbosity normal

  dotnet_publish:
    name: Generate and upload publish artifacts of .NET projects.
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.isCD != 'no')
    runs-on: ubuntu-latest
    needs: dotnet_CI
    strategy:
      fail-fast: false
      matrix:
        packages: 
        - IdentityServer:
          name: IdentityServer
          path: src/IdentityServer/src/UI
        
    steps:    
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
       
    - name: Restore and Build
      run: |
        dotnet tool restore
        dotnet restore "${{ matrix.packages.path }}"
        dotnet build "${{ matrix.packages.path }}" --configuration ${{ env.CONFIGURATION }} --no-restore    

    - name: Generate migrations efbundle
      continue-on-error: true
      run: |
        dotnet ef migrations bundle --configuration ${{ env.CONFIGURATION }} --no-build --verbose --context ApplicationDbContext --project "${{ matrix.packages.path }}" --output "${{ matrix.packages.path }}/efbundle" -r linux-x64
        dotnet ef migrations bundle --configuration ${{ env.CONFIGURATION }} --no-build --verbose --context ApplicationDbContext --project "${{ matrix.packages.path }}" --output "${{ matrix.packages.path }}/efbundle.exe" -r win-x64

    - name: Publish
      run: |
        dotnet publish "${{ matrix.packages.path }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ matrix.path }}/publish"

    - name: Upload Publish Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.packages.name }}
        path: ${{ matrix.packages.path }}/publish
  
  deploy_identityserver_on_stage:
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.isCD == 'stage') 
    runs-on: ubuntu-latest
    needs: dotnet_publish
    env:
      AZURE_WEBAPP_NAME: FinalProjectIdentityServer
      AZURE_WEBAPP_PACKAGE_PATH: src/IdentityServer/src/UI/publish
      AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.IdentityServer_Development_FFF }}
      AZURE_WEBAPP_PROJECT_PATH: src/IdentityServer/src/UI
      
    steps:    
    - name: Dowlload Publish Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: IdentityServer
        path: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}/publish
    - name: Deploy to Azure WebApp
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }} 