name: CI CD workflows

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/CI_CD.yml
      - src/IdentityServer/
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
    branches:
      - main
    paths:
      - .github/workflows/CI_CD.yml
      - src/IdentityServer/
  workflow_dispatch:   
 
env:
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 6.0.x
  SOLUTION_FILE: FinalProject.sln

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        Solution: 
        - IdentityServer:
          path: src/IdentityServer/FinalProject.IdentityServer.slnf
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

    - name: Restore
      run: |
        dotnet tool restore
        dotnet restore ${{ matrix.Solution.path }}

    - name: Build
      run: dotnet build "${{ matrix.Solution.path }}" --configuration ${{ env.CONFIGURATION }} --no-restore

    - name: Test
      run: dotnet test "${{ matrix.Solution }}" --no-build

  deploy_stage:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Staging'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    strategy:
      fail-fast: false
      matrix:
        Azure_WebApp:
          - IdentityServer:
            Name: FinalProjectIdentityServer
            Project_Path: src/IdentityServer/src/UI
            Package_Path: src/IdentityServer/src/UI/publish
            Publish_Profile: ${{ secrets.IdentityServer_Development_FFF }}
    steps:    
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
       
    - name: Restore and Build
      run: |
        dotnet tool restore
        dotnet restore ${{ matrix.Azure_WebApp.Project_Path }}
        dotnet build ${{ matrix.Azure_WebApp.Project_Path }} --configuration ${{ env.CONFIGURATION }} --no-restore
    
    - name: Publish
      run: |
        dotnet publish "${{ matrix.Azure_WebApp.Project_Path }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "matrix.Azure_WebApp.Package_Path"

    - name: Deploy to Azure WebApp
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ matrix.Azure_WebApp.Name }}
        package: ${{ matrix.Azure_WebApp.Package_Path }}
        publish-profile: ${{ matrix.Azure_WebApp.Publish_Profile }} 
