name: "Dotnet CD"

on:
  workflow_call:
    inputs:
      github_environment:
        description: The name of GitHub Environment for deployment
        type: string
        required: true
      publish_artifact_name:
        description: The name of publish artifact
        type: string
        required: true
      efbundle_artifact_name:
        description: The name of efbundle artifact
        type: string
        required: false
        default: ""
    secrets:
      AZURE_WEBAPP_NAME:
        description: The name of Azure Web App
        required: true
      AZUREAPPSERVICE_CLIENTID:
        description: The client ID for Azure App Service
        required: true
      AZUREAPPSERVICE_TENANTID:
        description: The tenant ID for Azure App Service
        required: true
      AZUREAPPSERVICE_SUBSCRIPTIONID:
        description: The subscription ID for Azure App Service
        required: true

jobs:
  deploy:
    name: "Deploy to Azure"
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.github_environment }}
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Download Publish Artifacts
        uses: actions/download-artifact@v5
        with:
          name: ${{ inputs.publish_artifact_name }}
          path: .

      - name: Download Efbundle Artifacts
        if: ${{ inputs.efbundle_artifact_name != '' }}
        uses: actions/download-artifact@v5
        with:
          name: ${{ inputs.efbundle_artifact_name }}
          path: efbundle

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure WebApp
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          package: .
