name: "Dotnet CI"

on:
  workflow_dispatch:
    inputs:
      github_environment:
        description: The name of GitHub Environment for deployment
        type: string
        required: true      
      publish_artifact_name:
        description: The name of publish artifact
        type: string
        required: true
      efbundle_artifact_name:
        description: The name of efbundle artifact
        type: string
        required: false
        default: ""
    secrets:
      AZURE_WEBAPP_NAME:
        description: The name of Azure Web App
        required: true
      AZURE_WEBAPP_PUBLISH_PROFILE:
        description: The XML publish profile of Azure Web App
        required: true
  workflow_call:

env:
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 6.0.x

jobs:
  deploy:
    name: "Deploy to Azure"
    runs-on: ubuntu-latest
    needs: dotnet_publish_IdentityServer
    environment:
      name: ${{ inputs.github_environment }}
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    env:
      AZURE_WEBAPP_NAME:  ${{ secrets.IDSV_NAME }}
      AZURE_WEBAPP_PROJECT_PATH: src/IdentityServer/src/UI
      AZURE_WEBAPP_PACKAGE_PATH: src/IdentityServer/src/UI/publish
      AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.PUBLISH_PROFILE_IDENTITYSERVER }}

    steps:
      - name: Download Publish Artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.publish_artifact_name }}
          path: .

      - name: Download Efbundle Artifacts
        uses: actions/download-artifact@v3
        if: ${{ inputs.efbundle_artifact_name != null }}
        with:
          name: inputs.efbundle_artifact_name
          path: efbundle/linux-x64