name: "Dotnet CD"

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      github_environment:
        description: The name of GitHub Environment for deployment
        type: string
        required: true
      publish_artifact_name:
        description: The name of publish artifact
        type: string
        required: true
      efbundle_artifact_name:
        description: The name of efbundle artifact
        type: string
        required: false
        default: ""
    secrets:
      AZURE_WEBAPP_NAME:
        description: The name of Azure Web App
        required: true
      AZURE_WEBAPP_PUBLISH_PROFILE:
        description: The XML publish profile of Azure Web App
        required: true

jobs:
  deploy:
    name: "Deploy to Azure"
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.github_environment }}
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Download Publish Artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.publish_artifact_name }}
          path: .

      - name: Download Efbundle Artifacts
        if: ${{ inputs.efbundle_artifact_name != '' }}
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.efbundle_artifact_name }}
          path: efbundle

      - name: Deploy to Azure WebApp
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          package: .
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
