name: "Development: CI"

on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - synchronize
      - reopened
  workflow_dispatch:

jobs:
  dotnet_CI:
    name: Run CI for .NET
    uses: ./.github/workflows/dotnet.ci.yml
    secrets: inherit
