name: "Development: CD"

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
    
jobs:
  dotnet_CI:
    name: Run CI for .NET
    uses: ./.github/workflows/dotnet.ci.yml
    secrets: inherit

  IdentityServer_CD:
    name: Run CD for Identity Server
    uses: ./.github/workflows/dotnet.cd.yml
    needs: [dotnet_CI]
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout
    with:
      github_environment: Development.IdentityServer
      publish_artifact_name: IdentityServer
      efbundle_artifact_name: IdentityServer.efbundle.linux-x64
    secrets: inherit

  DemoApp_Api_CD:
    name: Run CD for DemoApp Api
    uses: ./.github/workflows/dotnet.cd.yml
    needs: [dotnet_CI]
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout
    with:
      github_environment: Development.DemoApp
      publish_artifact_name: DemoApp.Api
    secrets: inherit
